-- Delete a user and every row that cascades from them (planner's events, guests,
-- invoices, etc.) plus nulling out rows that merely reference them (client_id,
-- assigned_to, uploaded_by, etc.) instead of being deleted.
-- Fill in the email below, then run this whole file against TiDB.

SET @uid = (SELECT id FROM users WHERE email = 'PUT_EMAIL_HERE');

-- 1) Null out references that shouldn't cascade-delete their own row
UPDATE `accommodation_bookings` SET `client_id` = NULL WHERE `client_id` = @uid;
UPDATE `accommodations` SET `owner_id` = NULL WHERE `owner_id` = @uid;
UPDATE `activity_logs` SET `user_id` = NULL WHERE `user_id` = @uid;
UPDATE `ai_prompt_versions` SET `created_by` = NULL WHERE `created_by` = @uid;
UPDATE `approval_history` SET `user_id` = NULL WHERE `user_id` = @uid;
UPDATE `approvals` SET `submitted_by` = NULL WHERE `submitted_by` = @uid;
UPDATE `auth_audit_logs` SET `user_id` = NULL WHERE `user_id` = @uid;
UPDATE `booking_requests` SET `vendor_id` = NULL WHERE `vendor_id` = @uid;
UPDATE `budgets` SET `approved_by` = NULL WHERE `approved_by` = @uid;
UPDATE `checkins` SET `checked_in_by` = NULL WHERE `checked_in_by` = @uid;
UPDATE `client_quotations` SET `client_id` = NULL WHERE `client_id` = @uid;
UPDATE `communication_logs` SET `created_by` = NULL WHERE `created_by` = @uid;
UPDATE `contracts` SET `vendor_id` = NULL WHERE `vendor_id` = @uid;
UPDATE `event_documents` SET `uploaded_by` = NULL WHERE `uploaded_by` = @uid;
UPDATE `event_milestones` SET `assigned_to` = NULL WHERE `assigned_to` = @uid;
UPDATE `event_tasks` SET `assigned_to` = NULL WHERE `assigned_to` = @uid;
UPDATE `events` SET `client_id` = NULL WHERE `client_id` = @uid;
UPDATE `expenses` SET `approved_by` = NULL WHERE `approved_by` = @uid;
UPDATE `expenses` SET `submitted_by` = NULL WHERE `submitted_by` = @uid;
UPDATE `invitations` SET `created_by` = NULL WHERE `created_by` = @uid;
UPDATE `invoices` SET `client_id` = NULL WHERE `client_id` = @uid;
UPDATE `message_threads` SET `vendor_id` = NULL WHERE `vendor_id` = @uid;
UPDATE `payments` SET `recorded_by` = NULL WHERE `recorded_by` = @uid;
UPDATE `quotations` SET `vendor_id` = NULL WHERE `vendor_id` = @uid;
UPDATE `receipts` SET `client_id` = NULL WHERE `client_id` = @uid;
UPDATE `refunds` SET `approved_by` = NULL WHERE `approved_by` = @uid;
UPDATE `refunds` SET `client_id` = NULL WHERE `client_id` = @uid;
UPDATE `reviews` SET `vendor_id` = NULL WHERE `vendor_id` = @uid;
UPDATE `saved_items` SET `vendor_id` = NULL WHERE `vendor_id` = @uid;
UPDATE `vendor_categories` SET `created_by` = NULL WHERE `created_by` = @uid;
UPDATE `vendors_assigned` SET `vendor_id` = NULL WHERE `vendor_id` = @uid;
UPDATE `venue_layouts` SET `created_by` = NULL WHERE `created_by` = @uid;
UPDATE `ai_actions` SET `ai_conversation_id` = NULL WHERE `ai_conversation_id` IN (SELECT id FROM `ai_conversations` WHERE `user_id` = @uid);
UPDATE `ai_generated_documents` SET `ai_template_id` = NULL WHERE `ai_template_id` IN (SELECT id FROM `ai_templates` WHERE `user_id` = @uid);
UPDATE `contracts` SET `booking_request_id` = NULL WHERE `booking_request_id` IN (SELECT id FROM `booking_requests` WHERE `planner_id` = @uid);
UPDATE `message_threads` SET `booking_request_id` = NULL WHERE `booking_request_id` IN (SELECT id FROM `booking_requests` WHERE `planner_id` = @uid);
UPDATE `quotations` SET `booking_request_id` = NULL WHERE `booking_request_id` IN (SELECT id FROM `booking_requests` WHERE `planner_id` = @uid);
UPDATE `invoices` SET `client_quotation_id` = NULL WHERE `client_quotation_id` IN (SELECT id FROM `client_quotations` WHERE `planner_id` = @uid);
UPDATE `reviews` SET `contract_id` = NULL WHERE `contract_id` IN (SELECT id FROM `contracts` WHERE `planner_id` = @uid);
UPDATE `accommodation_bookings` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `ai_actions` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `ai_automation_runs` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `ai_conversations` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `ai_feedback` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `ai_generated_documents` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `ai_meetings` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `ai_prompt_templates` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `booking_requests` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `client_quotations` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `contracts` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `invoices` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `message_threads` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `payment_schedules` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `payments` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `planner_booking_requests` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `planner_reviews` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `quotations` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `receipts` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `refunds` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `reviews` SET `event_id` = NULL WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
UPDATE `invitations` SET `template_id` = NULL WHERE `template_id` IN (SELECT id FROM `invitation_templates` WHERE `created_by` = @uid);
UPDATE `payment_schedules` SET `invoice_id` = NULL WHERE `invoice_id` IN (SELECT id FROM `invoices` WHERE `planner_id` = @uid);
UPDATE `payments` SET `invoice_id` = NULL WHERE `invoice_id` IN (SELECT id FROM `invoices` WHERE `planner_id` = @uid);
UPDATE `receipts` SET `invoice_id` = NULL WHERE `invoice_id` IN (SELECT id FROM `invoices` WHERE `planner_id` = @uid);
UPDATE `refunds` SET `invoice_id` = NULL WHERE `invoice_id` IN (SELECT id FROM `invoices` WHERE `planner_id` = @uid);
UPDATE `booking_requests` SET `venue_id` = NULL WHERE `venue_id` IN (SELECT id FROM `marketplace_venues` WHERE `owner_id` = @uid);
UPDATE `contracts` SET `venue_id` = NULL WHERE `venue_id` IN (SELECT id FROM `marketplace_venues` WHERE `owner_id` = @uid);
UPDATE `message_threads` SET `venue_id` = NULL WHERE `venue_id` IN (SELECT id FROM `marketplace_venues` WHERE `owner_id` = @uid);
UPDATE `quotations` SET `venue_id` = NULL WHERE `venue_id` IN (SELECT id FROM `marketplace_venues` WHERE `owner_id` = @uid);
UPDATE `reviews` SET `venue_id` = NULL WHERE `venue_id` IN (SELECT id FROM `marketplace_venues` WHERE `owner_id` = @uid);
UPDATE `saved_items` SET `venue_id` = NULL WHERE `venue_id` IN (SELECT id FROM `marketplace_venues` WHERE `owner_id` = @uid);
UPDATE `payments` SET `payment_schedule_id` = NULL WHERE `payment_schedule_id` IN (SELECT id FROM `payment_schedules` WHERE `planner_id` = @uid);
UPDATE `refunds` SET `payment_id` = NULL WHERE `payment_id` IN (SELECT id FROM `payments` WHERE `planner_id` = @uid);
UPDATE `contracts` SET `quotation_id` = NULL WHERE `quotation_id` IN (SELECT id FROM `quotations` WHERE `planner_id` = @uid);
UPDATE `marketplace_messages` SET `quotation_id` = NULL WHERE `quotation_id` IN (SELECT id FROM `quotations` WHERE `planner_id` = @uid);
UPDATE `expenses` SET `budget_item_id` = NULL WHERE `budget_item_id` IN (SELECT id FROM `budget_items` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid));
UPDATE `budget_items` SET `budget_id` = NULL WHERE `budget_id` IN (SELECT id FROM `budgets` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid));
UPDATE `ai_meeting_action_items` SET `task_id` = NULL WHERE `task_id` IN (SELECT id FROM `event_tasks` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid));
UPDATE `event_documents` SET `task_id` = NULL WHERE `task_id` IN (SELECT id FROM `event_tasks` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid));
UPDATE `seating_assignments` SET `guest_id` = NULL WHERE `guest_id` IN (SELECT id FROM `guests` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid));
UPDATE `rsvp_responses` SET `invitation_id` = NULL WHERE `invitation_id` IN (SELECT id FROM `invitations` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid) OR `guest_id` IN (SELECT id FROM `guests` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid)));
UPDATE `checkins` SET `qr_code_id` = NULL WHERE `qr_code_id` IN (SELECT id FROM `qr_codes` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid) OR `guest_id` IN (SELECT id FROM `guests` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid)));
UPDATE `budget_items` SET `vendor_assigned_id` = NULL WHERE `vendor_assigned_id` IN (SELECT id FROM `vendors_assigned` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid));
UPDATE `expenses` SET `vendor_assigned_id` = NULL WHERE `vendor_assigned_id` IN (SELECT id FROM `vendors_assigned` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid));
UPDATE `payment_schedules` SET `vendor_assigned_id` = NULL WHERE `vendor_assigned_id` IN (SELECT id FROM `vendors_assigned` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid));
UPDATE `payments` SET `vendor_assigned_id` = NULL WHERE `vendor_assigned_id` IN (SELECT id FROM `vendors_assigned` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid));
UPDATE `ai_actions` SET `ai_message_id` = NULL WHERE `ai_message_id` IN (SELECT id FROM `ai_messages` WHERE `ai_conversation_id` IN (SELECT id FROM `ai_conversations` WHERE `user_id` = @uid));

-- 2) Delete cascade-dependent rows, leaves first, users last
DELETE FROM `seating_assignments` WHERE `venue_object_id` IN (SELECT id FROM `venue_objects` WHERE `layout_id` IN (SELECT id FROM `venue_layouts` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid)));
DELETE FROM `venue_objects` WHERE `layout_id` IN (SELECT id FROM `venue_layouts` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid));
DELETE FROM `venue_images` WHERE `venue_id` IN (SELECT id FROM `marketplace_venues` WHERE `owner_id` = @uid);
DELETE FROM `venue_availability` WHERE `venue_id` IN (SELECT id FROM `marketplace_venues` WHERE `owner_id` = @uid);
DELETE FROM `task_dependencies` WHERE `depends_on_task_id` IN (SELECT id FROM `event_tasks` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid)) OR `task_id` IN (SELECT id FROM `event_tasks` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid));
DELETE FROM `saved_items` WHERE `collection_id` IN (SELECT id FROM `saved_collections` WHERE `planner_id` = @uid);
DELETE FROM `quotation_items` WHERE `quotation_id` IN (SELECT id FROM `quotations` WHERE `planner_id` = @uid);
DELETE FROM `invoice_items` WHERE `invoice_id` IN (SELECT id FROM `invoices` WHERE `planner_id` = @uid);
DELETE FROM `invitation_delivery_logs` WHERE `invitation_id` IN (SELECT id FROM `invitations` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid) OR `guest_id` IN (SELECT id FROM `guests` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid)));
DELETE FROM `client_quotation_items` WHERE `client_quotation_id` IN (SELECT id FROM `client_quotations` WHERE `planner_id` = @uid);
DELETE FROM `approval_history` WHERE `approval_id` IN (SELECT id FROM `approvals` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid));
DELETE FROM `ai_prompt_versions` WHERE `ai_prompt_template_id` IN (SELECT id FROM `ai_prompt_templates` WHERE `user_id` = @uid);
DELETE FROM `ai_messages` WHERE `ai_conversation_id` IN (SELECT id FROM `ai_conversations` WHERE `user_id` = @uid);
DELETE FROM `venues` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
DELETE FROM `venue_layouts` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
DELETE FROM `vendors_assigned` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
DELETE FROM `rsvp_responses` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid) OR `guest_id` IN (SELECT id FROM `guests` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid));
DELETE FROM `qr_codes` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid) OR `guest_id` IN (SELECT id FROM `guests` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid));
DELETE FROM `invitations` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid) OR `guest_id` IN (SELECT id FROM `guests` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid));
DELETE FROM `guests` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
DELETE FROM `guest_meal_preferences` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
DELETE FROM `expenses` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
DELETE FROM `event_tasks` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
DELETE FROM `event_milestones` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
DELETE FROM `event_documents` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
DELETE FROM `communication_logs` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid) OR `guest_id` IN (SELECT id FROM `guests` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid));
DELETE FROM `checkins` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid) OR `guest_id` IN (SELECT id FROM `guests` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid));
DELETE FROM `budgets` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
DELETE FROM `budget_items` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
DELETE FROM `approvals` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
DELETE FROM `ai_event_health_scores` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
DELETE FROM `activity_logs` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid);
DELETE FROM `vendor_services` WHERE `vendor_id` = @uid;
DELETE FROM `vendor_profiles` WHERE `user_id` = @uid;
DELETE FROM `vendor_portfolios` WHERE `vendor_id` = @uid;
DELETE FROM `vendor_packages` WHERE `vendor_id` = @uid;
DELETE FROM `vendor_availability` WHERE `vendor_id` = @uid;
DELETE FROM `user_roles` WHERE `user_id` = @uid;
DELETE FROM `tax_rules` WHERE `planner_id` = @uid;
DELETE FROM `task_comments` WHERE `task_id` IN (SELECT id FROM `event_tasks` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid)) OR `user_id` = @uid;
DELETE FROM `saved_collections` WHERE `planner_id` = @uid;
DELETE FROM `reviews` WHERE `reviewer_id` = @uid;
DELETE FROM `review_replies` WHERE `review_id` IN (SELECT id FROM `reviews` WHERE `reviewer_id` = @uid) OR `user_id` = @uid;
DELETE FROM `refunds` WHERE `planner_id` = @uid;
DELETE FROM `receipts` WHERE `payment_id` IN (SELECT id FROM `payments` WHERE `planner_id` = @uid) OR `planner_id` = @uid;
DELETE FROM `quotations` WHERE `planner_id` = @uid;
DELETE FROM `planner_reviews` WHERE `planner_id` = @uid OR `reviewer_id` = @uid;
DELETE FROM `planner_profiles` WHERE `user_id` = @uid;
DELETE FROM `planner_booking_requests` WHERE `client_id` = @uid OR `planner_id` = @uid;
DELETE FROM `payments` WHERE `planner_id` = @uid;
DELETE FROM `payment_schedules` WHERE `planner_id` = @uid;
DELETE FROM `notifications` WHERE `user_id` = @uid;
DELETE FROM `message_threads` WHERE `planner_id` = @uid;
DELETE FROM `marketplace_venues` WHERE `owner_id` = @uid;
DELETE FROM `marketplace_messages` WHERE `sender_id` = @uid OR `thread_id` IN (SELECT id FROM `message_threads` WHERE `planner_id` = @uid);
DELETE FROM `invoices` WHERE `planner_id` = @uid;
DELETE FROM `invitation_templates` WHERE `created_by` = @uid;
DELETE FROM `guest_categories` WHERE `created_by` = @uid;
DELETE FROM `events` WHERE `planner_id` = @uid;
DELETE FROM `event_categories` WHERE `created_by` = @uid;
DELETE FROM `direct_messages` WHERE `conversation_id` IN (SELECT id FROM `conversations` WHERE `user_one_id` = @uid OR `user_two_id` = @uid) OR `sender_id` = @uid;
DELETE FROM `conversations` WHERE `user_one_id` = @uid OR `user_two_id` = @uid;
DELETE FROM `contracts` WHERE `planner_id` = @uid;
DELETE FROM `client_quotations` WHERE `planner_id` = @uid;
DELETE FROM `client_profiles` WHERE `user_id` = @uid;
DELETE FROM `budget_categories` WHERE `created_by` = @uid;
DELETE FROM `booking_requests` WHERE `planner_id` = @uid;
DELETE FROM `ai_templates` WHERE `user_id` = @uid;
DELETE FROM `ai_recommendations` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid) OR `user_id` = @uid;
DELETE FROM `ai_prompt_templates` WHERE `user_id` = @uid;
DELETE FROM `ai_memories` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid) OR `user_id` = @uid;
DELETE FROM `ai_meetings` WHERE `user_id` = @uid;
DELETE FROM `ai_meeting_action_items` WHERE `ai_meeting_id` IN (SELECT id FROM `ai_meetings` WHERE `user_id` = @uid) OR `user_id` = @uid;
DELETE FROM `ai_knowledge_documents` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid) OR `user_id` = @uid;
DELETE FROM `ai_generated_documents` WHERE `user_id` = @uid;
DELETE FROM `ai_feedback` WHERE `user_id` = @uid;
DELETE FROM `ai_conversations` WHERE `user_id` = @uid;
DELETE FROM `ai_automation_runs` WHERE `ai_automation_rule_id` IN (SELECT id FROM `ai_automation_rules` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid) OR `user_id` = @uid) OR `user_id` = @uid;
DELETE FROM `ai_automation_rules` WHERE `event_id` IN (SELECT id FROM `events` WHERE `planner_id` = @uid) OR `user_id` = @uid;
DELETE FROM `ai_actions` WHERE `user_id` = @uid;
DELETE FROM `accommodation_reviews` WHERE `reviewer_id` = @uid;
DELETE FROM `accommodation_bookings` WHERE `planner_id` = @uid;
DELETE FROM `users` WHERE id = @uid;
