<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * A single AI recommendation generated by analysing an event's live data.
 * `signature` is a stable hash of (event, category, subject) so re-running the
 * engine updates the existing card instead of piling up duplicates.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('ai_recommendations', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained('users')->cascadeOnDelete();
            $table->foreignId('event_id')->nullable()->constrained('events')->cascadeOnDelete();
            $table->string('category');            // budget|timeline|vendor|guest|venue|financial|planning
            $table->string('title');
            $table->text('description');
            $table->string('priority')->default('medium'); // low|medium|high|critical
            $table->unsignedTinyInteger('confidence')->default(80); // 0–100
            $table->string('action_label')->nullable();
            $table->string('action_type')->nullable();   // navigate|none
            $table->json('action_payload')->nullable();  // e.g. route + params
            $table->string('status')->default('pending'); // pending|accepted|dismissed
            $table->string('signature')->index();
            $table->timestamp('resolved_at')->nullable();
            $table->timestamps();

            $table->unique(['event_id', 'signature']);
            $table->index(['user_id', 'status', 'priority']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('ai_recommendations');
    }
};
